export const skillsList = [
  { id: 1, skill: 'JavaScript', level: 'Intermediate' },
  { id: 2, skill: 'HTML/CSS', level: 'Advanced' },
  { id: 3, skill: 'Python', level: 'Intermediate' },
  { id: 4, skill: 'React', level: 'Advanced' },
  { id: 5, skill: 'Node.js', level: 'Intermediate' },
  { id: 6, skill: 'SQL', level: 'Intermediate' },
  { id: 7, skill: 'Java', level: 'Intermediate' },
  { id: 8, skill: 'C++', level: 'Beginner' },
  { id: 9, skill: 'Ruby', level: 'Intermediate' },
  { id: 10, skill: 'PHP', level: 'Intermediate' },
  { id: 11, skill: 'Swift', level: 'Beginner' },
  { id: 12, skill: 'Git', level: 'Advanced' },
  { id: 13, skill: 'Docker', level: 'Intermediate' },
  { id: 14, skill: 'Machine Learning', level: 'Intermediate' },
  { id: 15, skill: 'Data Analysis', level: 'Advanced' },
  { id: 16, skill: 'Angular', level: 'Intermediate' },
  { id: 17, skill: 'Vue.js', level: 'Intermediate' },
  { id: 18, skill: 'C#', level: 'Intermediate' },
  { id: 19, skill: 'Unity', level: 'Beginner' },
  { id: 20, skill: 'TensorFlow', level: 'Intermediate' },
  { id: 21, skill: 'Kubernetes', level: 'Intermediate' },
  { id: 22, skill: 'AWS', level: 'Advanced' },
  { id: 23, skill: 'Azure', level: 'Advanced' },
  { id: 24, skill: 'Google Cloud', level: 'Intermediate' },
  { id: 25, skill: 'Blockchain', level: 'Intermediate' },
  { id: 26, skill: 'DevOps', level: 'Advanced' },
  { id: 27, skill: 'UI/UX Design', level: 'Advanced' },
  { id: 28, skill: 'React Native', level: 'Intermediate' },
  { id: 29, skill: 'SwiftUI', level: 'Beginner' },
  { id: 30, skill: 'Cybersecurity', level: 'Intermediate' },
  { id: 31, skill: 'REST API', level: 'Intermediate' },
  { id: 32, skill: 'GraphQL', level: 'Intermediate' },
  { id: 33, skill: 'Linux', level: 'Intermediate' },
  { id: 34, skill: 'Bash Scripting', level: 'Intermediate' },
  { id: 35, skill: 'Rust', level: 'Beginner' },
  { id: 36, skill: 'Vue.js', level: 'Intermediate' },
  { id: 37, skill: 'Firebase', level: 'Intermediate' },
  { id: 38, skill: 'NoSQL Databases', level: 'Intermediate' },
  { id: 39, skill: 'Arduino', level: 'Beginner' },
  { id: 40, skill: 'IoT Development', level: 'Intermediate' },
  { id: 41, skill: 'Flutter', level: 'Intermediate' },
  { id: 42, skill: 'Xamarin', level: 'Intermediate' },
  { id: 43, skill: 'HTML5 Canvas', level: 'Intermediate' },
  { id: 44, skill: 'WordPress', level: 'Intermediate' },
  { id: 45, skill: 'Joomla', level: 'Intermediate' },
  { id: 46, skill: 'Drupal', level: 'Intermediate' },
  { id: 47, skill: 'Photoshop', level: 'Advanced' },
  { id: 48, skill: 'Illustrator', level: 'Advanced' },
  { id: 49, skill: 'InDesign', level: 'Intermediate' },
  { id: 50, skill: 'AutoCAD', level: 'Intermediate' },
  { id: 51, skill: '3D Modeling', level: 'Intermediate' },
  { id: 52, skill: 'Video Editing', level: 'Intermediate' },
  { id: 53, skill: 'Motion Graphics', level: 'Intermediate' },
  { id: 54, skill: 'Digital Marketing', level: 'Advanced' },
  { id: 55, skill: 'Copywriting', level: 'Intermediate' },
  { id: 56, skill: 'Content Strategy', level: 'Intermediate' },
  { id: 57, skill: 'Social Media Management', level: 'Advanced' },
  { id: 58, skill: 'Email Marketing', level: 'Intermediate' },
  { id: 59, skill: 'SEO', level: 'Advanced' },
  { id: 60, skill: 'Google Analytics', level: 'Intermediate' },
  { id: 61, skill: 'Project Management', level: 'Advanced' },
  { id: 62, skill: 'Agile Methodology', level: 'Intermediate' },
  { id: 63, skill: 'Scrum', level: 'Intermediate' },
  { id: 64, skill: 'Leadership', level: 'Advanced' },
  { id: 65, skill: 'Teamwork', level: 'Advanced' },
  { id: 66, skill: 'Problem Solving', level: 'Advanced' },
  { id: 67, skill: 'Communication', level: 'Advanced' },
  { id: 68, skill: 'Time Management', level: 'Advanced' },
  { id: 69, skill: 'Creativity', level: 'Advanced' },
  { id: 70, skill: 'Critical Thinking', level: 'Advanced' },
  { id: 71, skill: 'Analytical Skills', level: 'Advanced' },
  { id: 72, skill: 'Foreign Languages', level: 'Intermediate' },
  { id: 73, skill: 'Public Speaking', level: 'Advanced' },
  { id: 74, skill: 'Negotiation', level: 'Advanced' },
  { id: 75, skill: 'Financial Analysis', level: 'Intermediate' },
  { id: 76, skill: 'Data Visualization', level: 'Advanced' },
  { id: 77, skill: 'Statistical Analysis', level: 'Intermediate' },
  { id: 78, skill: 'Market Research', level: 'Intermediate' },
  { id: 79, skill: 'Customer Service', level: 'Advanced' },
  { id: 80, skill: 'Sales', level: 'Advanced' },
  { id: 81, skill: 'Retail Management', level: 'Intermediate' },
  { id: 82, skill: 'E-commerce', level: 'Intermediate' },
  { id: 83, skill: 'Supply Chain Management', level: 'Intermediate' },
  { id: 84, skill: 'Quality Assurance', level: 'Intermediate' },
  { id: 85, skill: 'Legal Research', level: 'Intermediate' },
  { id: 86, skill: 'Medical Diagnosis', level: 'Intermediate' },
  { id: 87, skill: 'Teaching', level: 'Advanced' },
  { id: 88, skill: 'Mentoring', level: 'Advanced' },
  { id: 89, skill: 'Public Relations', level: 'Intermediate' },
  { id: 90, skill: 'Event Planning', level: 'Intermediate' },
  { id: 91, skill: 'Graphic Design', level: 'Intermediate' },
  { id: 92, skill: 'Interior Design', level: 'Intermediate' },
  { id: 93, skill: 'Photography', level: 'Intermediate' },
  { id: 94, skill: 'Videography', level: 'Intermediate' },
  { id: 95, skill: 'Music Production', level: 'Intermediate' },
  { id: 96, skill: 'Another Skill', level: 'Beginner' },
  { id: 97, skill: 'Yet Another Skill', level: 'Advanced' },
  { id: 98, skill: 'One More Skill', level: 'Intermediate' },
  { id: 99, skill: 'Last Skill', level: 'Advanced' },
  { id: 100, skill: 'Final Skill', level: 'Intermediate' },
];

   


   export const data = [
    {
      id: 1,
      name: "Samaria",
    },
    {
      id: 2,
      name: "Gauthier",
    },
    {
      id: 3,
      name: "Mellisa",
    },
    {
      id: 4,
      name: "Arabela",
    },
    {
      id: 5,
      name: "Devon",
    },
    {
      id: 6,
      name: "Stacee",
    },
    {
      id: 7,
      name: "Federica",
    },
    {
      id: 8,
      name: "Jecho",
    },
    {
      id: 9,
      name: "Alasteir",
    },
    {
      id: 10,
      name: "Elston",
    },
  ];