export const skillsList = [
     { skill: 'JavaScript', level: 'Intermediate' },
     { skill: 'HTML/CSS', level: 'Advanced' },
     { skill: 'Python', level: 'Intermediate' },
     { skill: 'React', level: 'Advanced' },
     { skill: 'Node.js', level: 'Intermediate' },
     { skill: 'SQL', level: 'Intermediate' },
     { skill: 'Java', level: 'Intermediate' },
     { skill: 'C++', level: 'Beginner' },
     { skill: 'Ruby', level: 'Intermediate' },
     { skill: 'PHP', level: 'Intermediate' },
     { skill: 'Swift', level: 'Beginner' },
     { skill: 'Git', level: 'Advanced' },
     { skill: 'Docker', level: 'Intermediate' },
     { skill: 'Machine Learning', level: 'Intermediate' },
     { skill: 'Data Analysis', level: 'Advanced' },
     { skill: 'Angular', level: 'Intermediate' },
     { skill: 'Vue.js', level: 'Intermediate' },
     { skill: 'C#', level: 'Intermediate' },
     { skill: 'Unity', level: 'Beginner' },
     { skill: 'TensorFlow', level: 'Intermediate' },
     { skill: 'Kubernetes', level: 'Intermediate' },
     { skill: 'AWS', level: 'Advanced' },
     { skill: 'Azure', level: 'Advanced' },
     { skill: 'Google Cloud', level: 'Intermediate' },
     { skill: 'Blockchain', level: 'Intermediate' },
     { skill: 'DevOps', level: 'Advanced' },
     { skill: 'UI/UX Design', level: 'Advanced' },
     { skill: 'React Native', level: 'Intermediate' },
     { skill: 'SwiftUI', level: 'Beginner' },
     { skill: 'Cybersecurity', level: 'Intermediate' },
     { skill: 'REST API', level: 'Intermediate' },
     { skill: 'GraphQL', level: 'Intermediate' },
     { skill: 'Linux', level: 'Intermediate' },
     { skill: 'Bash Scripting', level: 'Intermediate' },
     { skill: 'Rust', level: 'Beginner' },
     { skill: 'Vue.js', level: 'Intermediate' },
     { skill: 'Firebase', level: 'Intermediate' },
     { skill: 'NoSQL Databases', level: 'Intermediate' },
     { skill: 'Arduino', level: 'Beginner' },
     { skill: 'IoT Development', level: 'Intermediate' },
     { skill: 'Flutter', level: 'Intermediate' },
     { skill: 'Xamarin', level: 'Intermediate' },
     { skill: 'HTML5 Canvas', level: 'Intermediate' },
     { skill: 'WordPress', level: 'Intermediate' },
     { skill: 'Joomla', level: 'Intermediate' },
     { skill: 'Drupal', level: 'Intermediate' },
     { skill: 'Photoshop', level: 'Advanced' },
     { skill: 'Illustrator', level: 'Advanced' },
     { skill: 'InDesign', level: 'Intermediate' },
     { skill: 'AutoCAD', level: 'Intermediate' },
     { skill: '3D Modeling', level: 'Intermediate' },
     { skill: 'Video Editing', level: 'Intermediate' },
     { skill: 'Motion Graphics', level: 'Intermediate' },
     { skill: 'Digital Marketing', level: 'Advanced' },
     { skill: 'Copywriting', level: 'Intermediate' },
     { skill: 'Content Strategy', level: 'Intermediate' },
     { skill: 'Social Media Management', level: 'Advanced' },
     { skill: 'Email Marketing', level: 'Intermediate' },
     { skill: 'SEO', level: 'Advanced' },
     { skill: 'Google Analytics', level: 'Intermediate' },
     { skill: 'Project Management', level: 'Advanced' },
     { skill: 'Agile Methodology', level: 'Intermediate' },
     { skill: 'Scrum', level: 'Intermediate' },
     { skill: 'Leadership', level: 'Advanced' },
     { skill: 'Teamwork', level: 'Advanced' },
     { skill: 'Problem Solving', level: 'Advanced' },
     { skill: 'Communication', level: 'Advanced' },
     { skill: 'Time Management', level: 'Advanced' },
     { skill: 'Creativity', level: 'Advanced' },
     { skill: 'Critical Thinking', level: 'Advanced' },
     { skill: 'Analytical Skills', level: 'Advanced' },
     { skill: 'Foreign Languages', level: 'Intermediate' },
     { skill: 'Public Speaking', level: 'Advanced' },
     { skill: 'Negotiation', level: 'Advanced' },
     { skill: 'Financial Analysis', level: 'Intermediate' },
     { skill: 'Data Visualization', level: 'Advanced' },
     { skill: 'Statistical Analysis', level: 'Intermediate' },
     { skill: 'Market Research', level: 'Intermediate' },
     { skill: 'Customer Service', level: 'Advanced' },
     { skill: 'Sales', level: 'Advanced' },
     { skill: 'Retail Management', level: 'Intermediate' },
     { skill: 'E-commerce', level: 'Intermediate' },
     { skill: 'Supply Chain Management', level: 'Intermediate' },
     { skill: 'Quality Assurance', level: 'Intermediate' },
     { skill: 'Legal Research', level: 'Intermediate' },
     { skill: 'Medical Diagnosis', level: 'Intermediate' },
     { skill: 'Teaching', level: 'Advanced' },
     { skill: 'Mentoring', level: 'Advanced' },
     { skill: 'Public Relations', level: 'Intermediate' },
     { skill: 'Event Planning', level: 'Intermediate' },
     { skill: 'Graphic Design', level: 'Intermediate' },
     { skill: 'Interior Design', level: 'Intermediate' },
     { skill: 'Photography', level: 'Intermediate' },
     { skill: 'Videography', level: 'Intermediate' },
     { skill: 'Music Production', level: 'Intermediate' },
   ];
   